### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by gmontalvo404** [vivekpanchal/HackerRankSolutions#14]
Can I organize the project folders? I feel that the repository has a bit of clutter and could confuse programmers if it is missing or if a specific exercise has already been done.

**Comment by vivekpanchal** [comment]
That would be really helpfull

**Comment by vivekpanchal** [comment]
- you should arrange everything according to the interview preparation kit  [HERE](https://www.hackerrank.com/interview/interview-preparation-kit)
- not according to Problem-solving

**Comment by gmontalvo404** [comment]
Ok
